### PR TITLE
Remove the JBoss Nexus repository.

### PR DESCRIPTION
**Pull request by jamezp**
Signed-off-by: James R. Perkins <jperkins@redhat.com>

### CODE REVIEW

**Comment by jamezp** [comment]
@jimma CI is now running on PR's, but I'm still trying to figure out why this is not updating the status. https://ci.wildfly.org/project/WildFlyProject_CXF?mode=builds

**Comment by jimma** [comment]
@jamezp We have to keep the nexus repository. The wss4j is still using a fork release: 
https://github.com/jboss/cxf/blob/3.5.2-jbossorg/parent/pom.xml#L234

**Comment by jamezp** [comment]
@jimma Okay, not worries. This was somewhat a test and a way to test the TeamCity PR pull player :)

**Pull request closed without merging**
